### ISSUE TITLE
Peer connection failure: pion server and werift client

### ISSUE THREAD

**Issue by sipsorcery** [sipsorcery/webrtc-echoes#12]
I'm logging this as a way to keep track of the tests I've run and where I'm yet to identify the cause of the failure.

Client and server applications are both being run on the same machine.

Operating System: Win 10 Pro x64 10.0.19042
node.js version: v14.15.5
go version: go1.14.4 windows/amd64

**server console log**
````
C:\Dev\sipsorcery\webrtc-echoes\pion>go build main.go && main.exe
Listening on 0.0.0.0:8080...
Signaling state has changed to have-remote-offer.
ICE connection state has changed to checking.
Signaling state has changed to stable.
ICE connection state has changed to failed.
Peer connection state has changed to failed.
Peer connection state has changed to closed.
ICE connection state has changed to closed.
````

**client console log**
````
C:\Dev\sipsorcery\webrtc-echoes\werift>npm run client

> werift-echo@1.0.0 client C:\Dev\sipsorcery\webrtc-echoes\werift
> ts-node-dev client

[INFO] 19:44:48 ts-node-dev ver. 1.1.1 (using ts-node ver. 9.1.1, typescript ver. 4.1.5)
````

**Comment by shinyoshiaki** [comment]
werift echo client depend on ffmpeg and GStreamer for make and show RTP media.
so you need to exec command below before `npm run client`

`ffmpeg -re -f lavfi -i testsrc=size=640x480:rate=30 -vcodec libvpx -keyint_min 30 -cpu-used 5 -deadline 1 -g 10 -error-resilient 1 -auto-alt-ref 1 -f rtp rtp://127.0.0.1:5000`

`gst-launch-1.0 -v udpsrc port=4002 caps = "application/x-rtp, media=(string)video, clock-rate=(int)90000, encoding-name=(string)VP8, payload=(int)97" ! rtpvp8depay ! decodebin ! videoconvert ! autovideosink`

**Comment by sipsorcery** [comment]
@shinyoshiaki thanks. I did spot you'd added those commands in the `client.ts` file and I did attempt to use them.

If I understand correctly it should work like this?

ffmpeg -> (udp: 5000) npm -> webrtc peer
webrtc peer -> npm (udp: 4002) -> gstreamer

**Comment by shinyoshiaki** [comment]
@sipsorcery 　That's correct

**Comment by sipsorcery** [comment]
@shinyoshiaki I did get the pipeline working with werift and the aiortc server. The ffmpeg test pattern gets through and is displayed by gstreamer.

`ffmpeg -> werift client -> aiortc echo server -> werift client -> gstreamer`

 - For the sipsorcery echo server we know it won't work due to no compatible ECDSA curve. ICE does connect.

 - For the pion echo server ICE does not connect. I suspect that's because the pion server is operating in trickle mode and therefore won't supply any ICE candidates to the `werift` client. The ICE candidates being supplied by `werift` on my Windows 10 machine won't work for local connections. The `0.0.0.0` and `[::]` candidate addresses aren't usable destinations on Windows (not 100% sure about Linux but I think it's the same).

````
a=candidate:47d1e387049b2478dab2534e99da8d18 1 udp 2130706431 0.0.0.0 63937 typ host
a=candidate:0ec0f0147bbc8b7f665a62b256fba95e 1 udp 2130706431 :: 63938 typ host
a=candidate:f38a4c448dc5a4e646a76902013b3d4a 1 udp 1694498815 37.228.228.227 30419 typ srflx raddr 0.0.0.0 rport 63937
````
 
 - For the werift echo server and werift client (I have run `npm install` since your latest commit) the video stream input does not reach gstreamer. The server and client debug messages are reporting `dtls connected` but I'm not so sure as if I do a Wireshark capture all I see are STUN messages.

werift server:

````
C:\Dev\sipsorcery\webrtc-echoes\werift>npm run server

> werift-echo@1.0.0 server C:\Dev\sipsorcery\webrtc-echoes\werift
> ts-node-dev server

[INFO] 21:47:01 ts-node-dev ver. 1.1.1 (using ts-node ver. 9.1.1, typescript ver. 4.1.5)
  werift/ice/ice ICE completed +0ms
  werift/dtls/flight/client/flight5 selected cipherSuite 49199 +0ms
  werift/webrtc/transport/dtls dtls connected +0ms
````

werift client:

````
C:\Dev\sipsorcery\webrtc-echoes\werift>npm run client

> werift-echo@1.0.0 client C:\Dev\sipsorcery\webrtc-echoes\werift
> ts-node-dev client

[INFO] 21:47:03 ts-node-dev ver. 1.1.1 (using ts-node ver. 9.1.1, typescript ver. 4.1.5)
  werift/ice/ice ICE completed +0ms
  werift/dtls/flight/server/flight2 cipher suite selected 49195 bad use 49199 (←todo fix) +0ms
  werift/webrtc/transport/dtls dtls connected +0ms
````

wireshark capture `udp portrange 49000-65535`:

![werift-capture](https://user-images.githubusercontent.com/197660/107996301-f8567700-6fd7-11eb-835f-5cc4e8763857.png)

**Comment by shinyoshiaki** [comment]
werift client x server pattern works in my environment.
I'll try this pattern later on Windows.

**Comment by shinyoshiaki** [comment]
> 0.0.0.0 and [::] candidate addresses
Fixed with the latest werift

**Comment by sipsorcery** [comment]
Pion server and werift client now connecting for me.

![pion-server_werift-client](https://user-images.githubusercontent.com/197660/108406417-51155200-721a-11eb-8583-7050fb1df9bf.png)
