### ISSUE TITLE
libdatachannel

### ISSUE THREAD

**Issue by paullouisageneau** [sipsorcery/webrtc-echoes#15]
Hello, author of [libdatachannel](https://github.com/paullouisageneau/libdatachannel) here.

This project is a very good idea to help democratize WebRTC! I think libdatachannel is a good candidate implementation to add to the tests. 

I see other implementations are fetched with package managers. As an old-fashion C++ project, the library itself is not on a generic package manager for now except from vcpkg (the rust, node.js, and unity wrappers are). I've been thinking about packaging it with conan, maybe I should do it before submitting a test server.

**Comment by sipsorcery** [comment]
Great, the more the merrier!

Personally I've used `vcpkg` a lot and if your library is available on it I for one will be able to build and run any apps that use it.

At this stage I think the idea is to go with the simplest bare minimum application for a WebRTC Echo Test server (and client if you're able). If you're already using a particular package manager and can provide some basic instructions that is likely to be enough for any interested parties to be able to run manual tests.

**Comment by Sean-Der** [comment]
So excited to have you involved @paullouisageneau ! This is going to be such a fantastic resource for the WebRTC community :)

**Comment by paullouisageneau** [comment]
OK, I'm preparing an echo test server and a client with a readme!
