### ISSUE TITLE
aiortc client echo test

### ISSUE THREAD

**Issue by sipsorcery** [sipsorcery/webrtc-echoes#18]
Need an aiortc client echo test to match the server one.

Client Echo Test [spec](https://github.com/sipsorcery/webrtc-echoes/blob/master/doc/EchoTestSpecification.md#client-peer-operation).

@jlaine in case you have bandwidth.

**Comment by jlaine** [comment]
I'll try and give it a shot next week, should be quite simple

**Comment by jlaine** [comment]
I'm having a look at this, and was wondering: what exactly do you want the client to send? Green frames for video and silence for audio?

**Comment by sipsorcery** [comment]
The client doesn't necessarily to send anything. At this point we're only testing up to the DTLS handshake completing.

But if it's easy to add media and doesn't involve including any tricky platform dependencies then there is certainly no harm in adding media.

**Comment by jlaine** [comment]
Ok in that case I think I'll send a single audio track with silence. If I offer no media, i would expect no media sections and hence no candidates?

**Comment by sipsorcery** [comment]
Sorry I haven't really described that very well.

For my client I do [make an offer](https://github.com/sipsorcery/webrtc-echoes/blob/dbab06a94e27b6fd99abe5dc5dc0c0c98338ded0/sipsorcery/client/Program.cs#L110) of PCMU audio but never actually send any. The client does need to make an offer with either an audio or video section so that the peer connection can proceed.

Once the client gets a successful DTLS handshake it can close the connection without ever having to send any media.

**Comment by jlaine** [comment]
OK, there is a basic client in #19, and I also included a `client.sh` which gets included in the docker image, so you *should* be able to just include `aiortc` as a client in the automated tests?
