### ISSUE TITLE
Timeout for werift Echo Test Client

### ISSUE THREAD

**Issue by sipsorcery** [sipsorcery/webrtc-echoes#22]
There have been a few instances where the automated tests with the `werift` client have gotten stuck. I don't know the reason yet. The consequence of getting stuck is that the GitHub Action Workflow will stay running for 6 hours before being killed by the CI server.

It'd be great if a timeout could be added to the `werift` client so that if the echo test does not work for whatever reason it exits with a failure code of `1` (or anything but `0`). The other two clients are using a 10s timeout.

Below is a screenshot of the action workflow if I change the Echo Test Server hostname so that the clients cannot send the SDP offer.

Note that all the echo tests failed. The green ticks are because the job continues on error and writes a failure result.

![werift-client-timeout](https://user-images.githubusercontent.com/197660/109031376-94f5d480-76bc-11eb-8380-6d8945d30d6d.png)

**Comment by shinyoshiaki** [comment]
I added some error handling at https://github.com/sipsorcery/webrtc-echoes/commit/4fb816f84c98e8c204c739db48755bf89a005e6f

If it happens again, please let me know.

**Comment by sipsorcery** [comment]
Will do, thanks for the quick fix.
