### ISSUE TITLE
Announcing/Publishing?

### ISSUE THREAD

**Issue by Sean-Der** [sipsorcery/webrtc-echoes#29]
Hey @sipsorcery 

You have done an amazing job, this is better than I had ever imagined :) What do you think of announcing this? You have done most of the work so your call. More people knowing about what you are doing would be great for this repo (and the WebRTC non-browser implementations)

These are the things that I think will excite people.
* WebRTC is available in more languages and is easier to use and deploy then ever before
* WebRTC does more then people expect (WebTorrent, IoT, Robotics)
* WebRTC has a healthy diverse community that works together
* ?

These are the places I have announced so far
* https://news.ycombinator.com/item?id=26622535
* https://www.reddit.com/r/WebRTC/comments/mftyp6/webrtcechoes_interop_for_c_c_python_typescript_go/
* https://twitter.com/_pion/status/1376561743871156225

These are the places I would love to announce
* /r/golang
* /r/python
* /r/csharp
* /r/typescript
* IETF mailing list

**Comment by sipsorcery** [comment]
@Sean-Der from my point of view I'm more than happy to see additional exposure. The more interest the better really. 

If you, or anyone else, thinks the repo would get a wider audience by hosting elsewhere, perhaps https://github.com/webrtc, I'm happy to transfer ownership.

It'd be particularly beneficial if a libwebrtc/webrtc.org developer got interested given it's the defacto standard. My [libwebrtc attempt](https://github.com/sipsorcery/webrtc-echoes/blob/master/libwebrtc/PcFactory.cpp) leaves a lot to be desired (in my defense it did literally take a week to get a usable build on Linux which used most of my time up).

**Comment by Sean-Der** [comment]
Sorry to hear you had to fight the libwebrtc stuff on your own :( please assign me issues/tasks, I really want to help!

It would be great if they got involved. I think it is very unlinkely though. It is more work for them with no reward.

----

Do you want to post this stuff everywhere? I am happy to write the copy! Or I can post?

**Comment by sipsorcery** [comment]
> Do you want to post this stuff everywhere? I am happy to write the copy! Or I can post?

If you could post any info you think would be worthwhile that'd be great. You're way more hooked into the ecosystem than me (I'm ashamed to say I don't even have a reddit account).

**Comment by Sean-Der** [comment]
@sipsorcery your life is probably better not having a reddit account :)

```
Show HN: webrtc-echoes: WebRTC Interop tests between C#, C++, Python, Typescript, Go and Servers.

Hey HN,

I am so excited to share webrtc-echoes. This repository contains a test suite that asserts that many different
WebRTC implementations can communicate with each other. It also asserts that these WebRTC implementations
work with WebRTC servers.

I think this is important for a few reasons
* Ensure that things connect, and prevents regressions. It makes all the implementations more robust.
* Great for learning. Developers see all the options available and can try different software.
* Builds community. With all of us working together it will help good ideas spread faster.

This is what is implemented today.
*   aiortc: WebRTC and ORTC implementation for Python using asyncio. [0] 
*   libdatachannel: C/C++ WebRTC Data Channels and Media Transport standalone library (bindings for Rust, Node.js, and Unity)
*   Pion: Pure Go implementation of the WebRTC API. [2]
*   SIPSorcery: A WebRTC, SIP and VoIP library for C# and .NET Core. Designed for real-time communications apps. [3]
*   werift-webrtc: WebRTC Implementation for TypeScript (Node.js) [4]

Servers:
* GStreamer's webrtcbin [5]
* Janus [6]
* Kurento [7]
* Google WebRTC [8]

[0] https://github.com/aiortc/aiortc
[1] https://github.com/paullouisageneau/libdatachannel
[2] https://github.com/pion/webrtc
[3] https://github.com/sipsorcery-org/sipsorcery
[4] https://github.com/shinyoshiaki/werift-webrtc
[5] https://gstreamer.freedesktop.org/documentation/webrtc/index.html
[6] https://janus.conf.meetecho.com/
[7] https://www.kurento.org/
[8] https://webrtc.googlesource.com/src/
```

**Comment by Sean-Der** [comment]
@shinyoshiaki @paullouisageneau @jlaine @sipsorcery  What do you think? Feel free to edit the comment directly. My only goal is to convince people this is interesting/important :)

**Comment by shinyoshiaki** [comment]
@Sean-Der 
Seems good! I have no objection to this sentence

**Comment by paullouisageneau** [comment]
@Sean-Der I think it looks perfect, thank you!

**Comment by Sean-Der** [comment]
Done! Really excited to see all the interest. I am going to ask for some help before I email the IETF list.
