### ISSUE TITLE
Implement automated testing

### ISSUE THREAD

**Issue by Sean-Der** [sipsorcery/webrtc-echoes#6]
* Run each implementation against every other
* Generate a table of results
* HTML-ize results

**Comment by sipsorcery** [comment]
The QUIC test approach mentioned by @jlaine seems pretty good as a starting point.

Something along the [same lines](https://github.com/marten-seemann/quic-network-simulator) of creating a docker image per WebRTC implementation seems like it could work?

**Comment by sipsorcery** [comment]
Done.
